spring.application.name=hospitalManagementSystem

server.port=8081

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDb

server.servlet.context-path=/api/v1

spring.datasource.username=postgres
spring.datasource.password=93489

# This will create schema on running your application and will also drop all schemas once you stop your application
spring.jpa.hibernate.ddl-auto=create

# TO see all the sql statements run by hibernate
spring.jpa.show-sql=true

#spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# Security Config
spring.security.user.name=sibu
spring.security.user.password=pass
